name: Release

on:
  push:
    branches: [main]

env:
  CI: true
  FORCE_COLOR: 3

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2

      - name: Setup
        uses: actions/setup-node@v3.4.1
        env:
          FORCE_COLOR: 0 # Weird bug: https://github.com/actions/setup-node/issues/317#issuecomment-1065124272
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          scope: '@gilderlabs'

      - name: Install dependencies
        run: yarn ci

      - name: Build
        run: yarn build:libs

      - name: Set .npmrc auth token
        run: |
          npm config set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Create and Publish Versions
        uses: changesets/action@v1
        with:
          version: yarn ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: yarn ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
